### ISSUE TITLE
Validator gives false "pass"

### ISSUE THREAD

**Issue by whmountains** [netlify/netlify-playground#13]
**- Do you want to request a *feature* or report a *bug*?**
I'm reporting a bug.

**- What is the current behavior?**
The following rules pass the validator, but don't work in practice

```
# Redirect /blog to /news and preserve query string
/blog post=:id  /news post=:id 302
```

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Add `/blog post=:id  /news post=:id 302` to your `_redirects` file
2. Visit `https://yoursite.netlify.com/blog?id=1`
3. You'll get a 404 page instead of the redirect.

**- What is the expected behavior?**
The rules shouldn't pass validation, because the syntax is wrong.  The correct syntax (found through trial and error) is:

```
/blog post=:id  /news?post=:id 302
```

Notice the space is replaced with a question mark.

**- Please mention your Elm, node.js, and operating system version.**
Not applicable because I'm not working with the source code.

**Comment by calavera** [comment]
We'll take a look, thanks!
