### ISSUE TITLE
Don't urlescape ":splat"

### ISSUE THREAD

**Issue by Pilskalns** [netlify/netlify-playground#23]
**- Do you want to request a *feature* or report a *bug*?**
A bug.

**- What is the current behavior?**
Playground generates rule for `netlify.toml` with url-escaped `:` as `%3A`in path, which shouldn't be.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Test following syntax:
```
http://domain.com/* https://domain.com/:splat/
```
And output will be:
``` ini
[[redirects]]
from = "http://domain.com/*"
to = "https://domain.com:443/%3Asplat"
status = 301
force = true
```
This will redirect literally to `https://domain.com/%3Asplat`

**- What is the expected behavior?**
The output path shouldn't be url-escaped:
``` ini
[[redirects]]
from = "http://domain.com/*"
to = "https://domain.com:443/:splat"
status = 301
force = true
```

**Comment by calavera** [comment]
ugh, thanks for reporting this 👍

**Comment by JokerQyou** [comment]
Actually all placeholders are currently urlencoded, not only the `:splat`.
