### ISSUE TITLE
Broken on Safari

### ISSUE THREAD

**Issue by bdougie** [netlify/netlify-playground#7]
Just visited the play.netlify.com on Safari and noticed it was broken. The error in the console is complaining about the use of `const` on this [line](https://github.com/netlify/netlify-playground/blob/master/src/Native/Ace.js#L146).

I can look into this later, but want to make you aware. 

<img width="949" alt="screenshot 2016-10-25 09 43 04" src="https://cloud.githubusercontent.com/assets/5713670/19695296/7958bf86-9a97-11e6-80c4-96b2cebbb8b7.png">

**Comment by calavera** [comment]
fixed in #8.
